# Generated by Django 5.1.3 on 2024-11-27 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kullanıcılar",
            fields=[
                ("kullanici_id", models.AutoField(primary_key=True, serialize=False)),
                ("kullanici_adi", models.CharField(max_length=150, unique=True)),
                ("sifre", models.CharField(max_length=128)),
                ("e_posta", models.EmailField(max_length=254, unique=True)),
                ("konum", models.CharField(blank=True, max_length=255, null=True)),
                ("ad", models.CharField(blank=True, max_length=100, null=True)),
                ("soyad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dogum_tarihi",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("cinsiyet", models.CharField(blank=True, max_length=10, null=True)),
                ("telefon_no", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "profil_fotograf",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
            ],
            options={
                "db_table": "kullanıcılar",
            },
        ),
        migrations.CreateModel(
            name="GenelMesaj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mesaj_metni", models.TextField()),
                ("gonderim_zamani", models.DateTimeField(auto_now_add=True)),
                (
                    "gonderici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("birth_date", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Erkek"), ("F", "Kadın")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("photo", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
