# Generated by Django 5.1.2 on 2024-11-29 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanıcılar',
            name='user',
            field=models.OneToOneField(default=150, on_delete=django.db.models.deletion.CASCADE, related_name='kullanici', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
